// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLHocPhan_23TH0003.Data;

#nullable disable

namespace QLHocPhan_23TH0003.Data.Migrations.QLHocPhan
{
    [DbContext(typeof(QuanLyHocPhanDbContext))]
    partial class QuanLyHocPhanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.DangKyHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLopHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("IdSinhVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("DangKyHocPhan", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemThucHanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDangKyHocPhan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("XepLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDangKyHocPhan")
                        .IsUnique();

                    b.ToTable("Diem", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaGiangVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhoa");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.HocKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaHocKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HocKy", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.HocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdHocKy")
                        .HasColumnType("int");

                    b.Property<int>("IdMonHoc")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHocKy");

                    b.HasIndex("IdMonHoc");

                    b.ToTable("HocPhan", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdTruongKhoa")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTruongKhoa")
                        .IsUnique()
                        .HasFilter("[IdTruongKhoa] IS NOT NULL");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhoa");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.LopHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiemHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeSoChuyenCan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HeSoCuoiKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HeSoGiuaKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HeSoThucHanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdHocPhan")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaLopHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLopHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHocPhan");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhoa");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.PhanCongGiangDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("IdLopHocPhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGiangVien");

                    b.HasIndex("IdLopHocPhan");

                    b.ToTable("PhanCongGiangDay", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdLop")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLop");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.DangKyHocPhan", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("IdLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLHocPhan_23TH0003.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("IdSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Diem", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.DangKyHocPhan", "DangKyHocPhan")
                        .WithOne("Diem")
                        .HasForeignKey("QLHocPhan_23TH0003.Models.Diem", "IdDangKyHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyHocPhan");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.GiangVien", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("IdKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.HocPhan", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.HocKy", "HocKy")
                        .WithMany("HocPhans")
                        .HasForeignKey("IdHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLHocPhan_23TH0003.Models.MonHoc", "MonHoc")
                        .WithMany("HocPhans")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Khoa", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.GiangVien", "TruongKhoa")
                        .WithOne()
                        .HasForeignKey("QLHocPhan_23TH0003.Models.Khoa", "IdTruongKhoa");

                    b.Navigation("TruongKhoa");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Lop", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.Khoa", "Khoa")
                        .WithMany("Lops")
                        .HasForeignKey("IdKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.LopHocPhan", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.HocPhan", "HocPhan")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.MonHoc", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.Khoa", "Khoa")
                        .WithMany("MonHocs")
                        .HasForeignKey("IdKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.GiangVien", "GiangVien")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLHocPhan_23TH0003.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.SinhVien", b =>
                {
                    b.HasOne("QLHocPhan_23TH0003.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdLop");

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.DangKyHocPhan", b =>
                {
                    b.Navigation("Diem");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.GiangVien", b =>
                {
                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.HocKy", b =>
                {
                    b.Navigation("HocPhans");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.HocPhan", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("Lops");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.LopHocPhan", b =>
                {
                    b.Navigation("DangKyHocPhans");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.MonHoc", b =>
                {
                    b.Navigation("HocPhans");
                });

            modelBuilder.Entity("QLHocPhan_23TH0003.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
