//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_23TH0003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ClassID { get; set; }
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
        public byte Semester { get; set; }
        public int Year { get; set; }
        public Nullable<int> HeSo_Diem1 { get; set; }
        public Nullable<int> HeSo_Diem2 { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
